name: lunegpt  # MUST be lowercase
description: Elite Intelligence optimized by Adam Aghnia.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  llama_flutter_android: any 
  path_provider: any
  cupertino_icons: any

flutter:
  uses-material-design: true
