name: LuneGPT
description: Elite Intelligence optimized by Adam Aghnia.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  llama_flutter_android: ^1.1.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
