name: Build LuneGPT
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Regenerate and Fix SDK
        run: |
          rm -rf android
          # We use the lowercase name here to match pubspec
          flutter create . --platforms android --project-name lunegpt
          
          # This magic line finds 'minSdkVersion' and changes it to 26
          sed -i 's/minSdkVersion .*/minSdkVersion 26/' android/app/build.gradle
          
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.0.12077973"

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LuneGPT-Release
          path: build/app/outputs/flutter-apk/app-release.apk
